global radii

% for n = 1:numberOfPlanets
%       if n == 1
%           image = imread('planets\sun.jpg');
%       else
%           image = imread('planets\earth.jpg');
%       end
%       hold on
%       [x,y,z] = sphere;
%       r = radii(n);
%       planets = surf(x*r + pos_x,...
%                      y*r + pos_y,...
%                      z*r + pos_z,...
%                      flipud(image),...
%                     'FaceColor','texturemap',...
%                     'EdgeColor','none');
%       hold off
%   end
image = imread('planets\earth.jpg');
[x, y, z] = sphere(50);
r = radii(3);
xlim([-1e2, 1e2]);
ylim([-1e2, 1e2]);
zlim([-1e2, 1e2]);
[~, pos, ~] = body_elements_and_sv(3, 2020, 01, 01, 0, 0, 0);

pl = surf(x*r/100,...
               y*r/100,...
               z*r/100,...
               flipud(image),...
               'FaceColor','texturemap',...
               'EdgeColor','none');